import os
from unittest import TestCase
from StringIO import StringIO

from idfastq.fastq_summary import FastqSummary

testdata = """@HWI-ST0787:147:C24LTACXX:1:1101:1220:2075 1:N:0:TCCTGAGC
GCTTAAACCACTCATTAAAGGTTTCATGGGCTTCCAAATAAGCTCTGATGCACAAATGTTCTAGGATAGCACTATCATCTTCAGAAGGAAGTGGACTTTC
+
=;?DDAADFF?CFDFG>BHHIA:CE@F?EG3?F?E*:CFHED?BDHIEEE<FHI@BD@FA8=/=FGGCH48@=CECA@AEH;7=)7@B2>>ACCACCCC>
@HWI-ST0787:147:C24LTACXX:1:1101:1246:2083 1:N:0:TCCTGAGC
ATACTGTGAATAGTCCCTCCCAAACTTTCAATAATTTCCTGAATCTCATCAAAATCTAAATTATTCCCTTCAATTGTAACTTTAACATTCTCAGTCTCTT
+
@@@DBDDDHFFGDGG@FGBGGIGFIEHHCFAFE<CFBEF@CHCHGIHIIIIIDGGCHEDFHIIIG>4BFGH:@CGEGHDDEGGAEEHHH?CDFEFFFEEE
@HWI-ST0787:147:C24LTACXX:1:1101:1206:2206 1:N:0:TCCTGAGC
TAACTACTCTGGGGTGGCAGGTTCCAGAGAATGCAGTAGACCTTTTGCCACTCATCTGTGTTTTACTTGAGACATGTAAATATGATAGCTGTCTCTTATA
+
@@@FFDDDCFFHHIGGBE3FFCFIGIG<DGDCGBDF?FCFBB?DFFG<FG>FFEHFFEEGEHHFEFHEE?;?DFCCEC@>;6>C>C;>>@AC:A>ACCC:
@HWI-ST0787:147:C24LTACXX:1:1101:1300:2098 1:N:0:TCCTGAGC
AGCCAGGGCTTACCTGTACACTGACTTGAGACCAGTTGAATAAAAGTGCACACCTTGAAAAAAAAAAAAAAAAAAAAAAAAAAAGACTTTTTGTTTTAAT
+
?@@FFDFFBAFBFEGEHDGHGCFEHHHGEEDGG3CB<D*?FDFHGI?DHAFHBFHGICFGB9BHFCBBBB9>@>BB<B><B###################
@HWI-ST0787:147:C24LTACXX:1:1101:1273:2121 1:N:0:TCCTGAGC
GTTTGAGACAGCTTCACCTTGAACTTTGAATTTATCAGCAGCTGCTAGTTGTGCTTGCTGGGATAAATCTTCGATCTTGGCTTCCCCAAAAACTATGTAA
+
?@@DDD7=+2A:CCFFIBGEH@FEFHFD4+2?G*?:?:?BB?;FCF9B?DFIIFFIIICAFF>=FCAF;D;)==D=?CEE@B@))6;3??==;AABBA@B
@HWI-ST0787:147:C24LTACXX:1:1101:1304:2133 1:N:0:TCCTGAGC
TGTATAAAGTGCTGGTGTGTGACCATCCTTTGGGGAAGGTCAAAGGGGGCAAGATCCCCAGGGGACCTGAGGAAGGGCAGGGCATAGGCGTGGCTCCCAG
+
@@@DDDDEHHDHFII3CAF@FA4FBFH>?FCHG@G1:?@9?FHIIIIIIHBHIEHA;C?@?B<A',5=<?C?>A?198?9<@BBCCCCC>BBB&8:2?9:
@HWI-ST0787:147:C24LTACXX:1:1101:1280:2157 1:N:0:TCCTGAGC
GTATCAACGCAGAGTACATGGGAGCTGTTTCATATGGACCCATCTGGGACCTTTGTACAGTGTGATGCTCGAGCAATTGGCTCTGCTTCAGAGGGTGCCC
+
@@@DDDFFHD<@CGFDHGIIJGGGHIHGHJCDGBGGHHGIGIIJHHJJFHIGIJIJFHIIFGDHHIJIHEH?DECA>CEDCCCDDDCDAACCDDD<@<A3
@HWI-ST0787:147:C24LTACXX:1:1101:1441:2189 1:N:0:TCCTGAGC
GGATGTTCGTCGTGGCAACGTTGCTGGTGACAGCAAAAATGACCCACCAATGGAAGCAGCTGGCTTCACTGCTCAGGTGATTATCCTGAACCATCCAGGC
+
CCBFFFFFHHHHHJJJJJIJIJJJJJJFHHHGHIIIJJJJCFIJE.B5@(8BCA7@6.76=?;5;;;(.;6(-5(-;(5(5@(5>(5:A@C1+4?8(:9A
@HWI-ST0787:147:C24LTACXX:1:1101:1355:2215 1:N:0:TCCTGAGC
TTTCTGGAAACTGCCTCGTCATGCGACTGTTCCCCGGGGTCAGGGCCGCTGGTATTTGCTGTAAAGAGGGGCGTTGAGTCCGTCCGACTTCACTGCCCCC
+
=??DDDDDADBDB:2A:@E3ABFAFBEEDDD4CBDDAD:A'.==A((5=@@@5-;>>BBAA#######################################
"""

testdata2 = """@HWI-ST926:235:C1JE0ACXX:1:1101:1101:1968 1:N:0:CGTACTA
NTGTTGGAACTCTACCAATTGGAGCTTTCTTAGCTGTCTTAGCAGTAGTTTATAAGGAATATATCCCATTTTTAGTTATAATGATGCCTTATGTGATAGA
+
#1=BDFFDABHHHIIIIIIIIIIICIGIIIIIIIIIIGHIIIBDHDGGHHGGGGHIIIIIIIIIAHIIFGEDFGE@=DGEEEFHHHEHFFFEFFDDEEA@
@HWI-ST926:235:C1JE0ACXX:1:1101:1089:1984 1:N:0:CGTACTA
NAATAGCCTAGAGTGGGAGTTAGGAAAAGTTAAGGCAGAGACATGTCCATGTATAAGCTATGCTGTTTTTACAAAAAACAGATGGGTGTTGGCTATTTAG
+
#1=DDFFFHHHHGCFGIFHGHGIJGIIIJHIJIIIEGIEHGGIJIIIIJJIHIJJIIJIJIJJJJFHIJJJJJHHHHFDAEEEDDD??BDDDDDDDDEED
@HWI-ST926:235:C1JE0ACXX:1:1101:1391:1984 1:N:0:CGTACTA
NGGGAGGTGGTAGCATTGCTTTCGTGTAAATTATGTAATGCAAAATTTTTTTAATCTTCGCCTTAATACTTTTTTATTTTGTTTTATTTTGAATGATGAG
+
#4=DBDD<CHFHHIJJJJJJJJJJFHHIJJJJJJJHIJJJJJJJIIJJJJJJGIJJJJJJJHHHFFFFFFEEEEDDCDEEDDDDDDDDEEDDDDDCDDED
@HWI-ST926:235:C1JE0ACXX:1:1101:1517:1968 1:N:0:CGTACTA
NCAGGGGGAGTAAGTGCTTATTCTGCCCTTCCTATATCTAGGCCACTTAATTACTATTTTCTTGGCTCTAAAGAGACAGAAGCCAACTAACAAGTCCGGC
+
#4=DDFFFDHHHHJGHIJJJJJJIJJJJIIJIJIJIJGGIIIJJJJIIIJJJIJJJIIJJJJJJHHHHHFFFFFFEECEEDDCDDDDDDDDDDDACDDDD
@HWI-ST926:235:C1JE0ACXX:1:1101:1731:1971 1:Y:0:CGTACTA
NAGGTGGGGACTTCAGAGCTCAGGAATGTAAAGGAAGGGCGGCGGACCGAGCCCTGGGGCTCTCAGGGGGCTGGAATGGTTAAAGCACAGCTGAGAACCT
+
#1=?4A;DDDDDDIEEIIEEIEEEEEEIEIIDIADDDDI=DDA@A?::<555<?=?=?<???AAAA><>>>>>>?AAAA:>AAAA>A????AAA?(4>??
@HWI-ST926:235:C1JE0ACXX:1:1101:1610:1990 1:N:0:CGTACTA
NGTCACTACGGGTCAAACATGAAGAAGTCAGCATCTAACAGTGAAAACGGGCGGCTTATAACAGCATCAAGAGAGAAGGCCAGCCACATGCACAGTGGTA
+
#1:BDDDDFFDFHIIIIIIFI>EEGHICDHG>EGGGIIFIIBGECDHCGEHGG??BBCCCECCC?CCCCCCCBCB?C??@?BBBBBCBCCCCCCC:CC:>
@HWI-ST926:235:C1JE0ACXX:1:1101:1716:1999 1:N:0:CGTACTA
CATCTAGGCATGGAATCTTATGCCAGCTAACGGAACAAGCTTTGTGCCATTCGGACCTACCGTAAGCCTATATTTCGTTTTTCTGAGACCTATCCGAGTT
+
@CCFDFFFBFHHHHIIEIFGIIIIHIIJJIEGGHIIJIEIGIJIFHIIJIEIIG;FGIJJIJGCHEDFFFFFEFFCCCCDBDDDCDDCDDDDDDDDDDDB
@HWI-ST926:235:C1JE0ACXX:1:1101:2022:1981 1:N:0:CGTACTA
NACAAAAAGAGGAGCAGAAGAAACTCGAGGAGCTAAAAGCGAAGGCCGCGGGGAAGGGGCCCTTGGCCACAGGTGGAATTAAGAAATCTGGCAAAAAGTA
+
#4BDFFFFHHHGFIJJJIJIJJJJJJJGJJJJJJJJJJIIIIJIIJJIIFDDDBDDDDDBDDDDDCDDDDDDD:@??CDDDDDDDDDDDEDDDD?CDDCC
@HWI-ST926:235:C1JE0ACXX:1:1101:2087:1989 1:N:0:CGTACTA
NCGATACTCATCCCGAACCTGGCCCCCGGATCGCCCACGGCCGTATTGCCTGCCCTCCTTAAAGCCTGCGTTGATACCTGTCTCTTATACACATCTCCGA
+
#4:BDDDDDHFHFIIBGIGE<;E9CFG>FG<F<1@GA5@BE<>39?;(>A>3<5,,9<CC3::3:<@BBB5?-8:(4>:C@C@C:@CC@3>:AACC>AB#
@HWI-ST926:235:C1JE0ACXX:1:1101:2066:1993 1:N:0:CGTACTA
GCAAATCTGTGAATGGCGACTATGCGCCTAGTCAACCAGATGTGTGCTAGCCCGTCGAGACTGAAAAGCTATAACCCGCAGACCCGAGCGAAAGCGGCGG
+
CCCFFFFFHHHHHJJJJJJJJJJJIJJJJJJIJJJJIJJJIJIIFHIJJJJJJJHIHFHFFFFEEEEEDDDDEDDCDDDDDDDDDDBDDDBDDBDDDDDD
"""



class TestFastqSummary(TestCase):
    def test_pretty_serialization(self):
        fastq = StringIO(testdata)
        summary = FastqSummary('fake_name')
        summary.read_fastq(fastq)

        report = summary.__repr__pretty__()

        summary2 = FastqSummary()
        summary2.parse_pretty(report.split(os.linesep))

        self.assertEqual(summary.filename, summary2.filename)
        self.assertEqual(summary.md5sum, summary2.md5sum)
        self.assertEqual(summary.reads, summary2.reads)
    
    def test_distance(self):
        a = FastqSummary('a')
        alpha = FastqSummary('alpha')
        beta = FastqSummary('beta')
        other = FastqSummary('other')

        a.read_fastq(StringIO(testdata))
        alpha.read_fastq(StringIO(testdata))
        beta.read_fastq(StringIO(testdata[:786]))
        other.read_fastq(StringIO(testdata2))

        print(a.__repr__pretty__())
        print(beta.__repr__pretty__())
        print(testdata[:786])
        # these two are the same
        self.assertEqual(a.distance(a), 0)
        # these two should be the same
        self.assertEqual(a.distance(alpha), 0)
        # this is a subset
        self.assertAlmostEqual(a.distance(beta), 2.0/3.0)
        # should be completely unreleated
        self.assertEqual(a.distance(other), 1)

        
